<?php 
use Classes\Common;
if (!empty($configError)) { 
?>
<span class="hidden unseen-notification" data-title="Configuration Notice" data-status="error">
	<?php print $configError; ?>
</span>
<?php } ?>

<div class="card text-secondary">
	<div class="card-header">
		Configure Git Source
	</div>
	<div class="card-body">
		<p class="card-text">Select the git source type, then confiure it.</p>
		<form class="form" id="connection-config">
			<div class="form-group">
				<label class="control-label" for="git-source-select">Git Source</label>
				<select class="select form-control" id="git-source-select" name="git-source-select">
					<option>Select a Git Source...</option>
					
					<?php foreach ($connections as $idx => $connection) { ?>
					<option value="<?php print intval($idx) ?>"><?php print $connection['name'] ?> </option>
					<?php } ?>
					
				</select>
			</div>
			
			<div class="form-group">
				<label class="control-label" for="git-api-url">Git API URL</label>
				<input class="form-control" type="text" id="git-api-url" name="git-api-url" placeholder="required" />
			</div>
			<div class="form-group">
				<label class="control-label" for="git-file-url">Git Files URL</label>
				<input class="form-control" type="text" id="git-file-url" name="git-file-url" placeholder="optional" />
			</div>
			<div class="form-group">
				<label class="control-label" for="git-source-auth">Authorization Type</label>
				<select class="select form-control" id="git-source-auth" name="git-source-auth">
					<option value="none">Select an Authorization method...</option>
				</select>
			</div>
			
			<?php foreach ($authTypes as $idx => $authType) { ?>
			<div class="auth-type-container border rounded" data-for="<?php print $auth_type['auth_name'] ?>">
				<?php
				    for ($i = 1; $i < 3; $i ++) {
				        if (!empty($auth_type['auth_field_' . $i])) {
				            $authField = $authType['auth_field_' . $i];
				            $authFieldText = Common::fieldToUserText($authType['auth_field_' . $i]);
				            print Common::getPartialView('auth_type_field', [$authField, $authFieldText]);
    				    }
    			     } 
    			 ?>
    		</div>
    		<?php } ?>
    		
    		<div class="button-bar">
    			<button type="button" id="connection-test" class="btn btn-primary">Test Connection</button>
    			<button type="button" id="config-save" class="btn btn-success hidden">Save Configuration</button>
    		</div>
		</form>
	</div>
</div>