<?php
use Classes\Common;
?>

	<script src="<?php print Common::cache('/js/vendor/jquery.min.js'); ?>"></script>
	<script src="<?php print Common::cache('/js/vendor/popper.min.js'); ?>"></script>
	<script src="<?php print Common::cache('/js/vendor/bootstrap.min.js'); ?>"></script>
	<script src="<?php print Common::cache('/js/vendor/select2.min.js'); ?>"></script>
	<script src="<?php print Common::cache('/js/release-manager.min.js'); ?>"></script>
	
	<script type="text/javascript">
		$(document).ready(function() {
			App.releaseManager();
			App.connector();
			App.notifier();
		});
	</script>
</body>
</html>
