<?php
use Classes\Common;
?>
<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title><?php print $pageTitle; ?></title>

	<link rel="stylesheet" href="<?php print Common::cache('/css/vendor/bootstrap.min.css'); ?>" />
	<link rel="stylesheet" href="<?php print Common::cache('/css/vendor/materialdesignicons.min.css'); ?>" media="all" />
	<link rel="stylesheet" href="<?php print Common::cache('/css/vendor/select2.min.css'); ?>" />
	<link rel="stylesheet" href="<?php print Common::cache('/css/release-manager.min.css'); ?>" />
</head>

<body>
